version: '3'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
      - redis-user-fast
      - redis-user-slow

  redis:
    image: 'redis:latest'

  redis-user-fast:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis-user-slow:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
