version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
    hostname: my-web-container

  slow-worker:
    build:
      context: .
      dockerfile: src/slow/workers/slow-worker/slow.worker.dockerfile
    depends_on:
      - redis
    hostname: my-slow-container
    ports:
      - "6378:6379"

  
  fast-worker:
    build:
      context: .
      dockerfile: src/slow/workers/fast-worker/fast.worker.dockerfile
    depends_on:
      - redis
    hostname: my-fast-container

  redis:
    image: redis:alpine
    ports:
      - '6377:6379'
