version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
    hostname: my-web-container

  slow-worker:
    build:
      context: .
      dockerfile: src/workers/slow.worker.dockerfile
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
