version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
    hostname: my-web-container

  slow-worker:
    build:
      context: .
      dockerfile: Dockerfile.slow

  
  fast-worker:
    build:
      context: .
      dockerfile: Dockerfile.fast