version: '3'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
      - redis-user-slow

  redis:
    image: 'redis:latest'

  redis-user-slow:
    build:
      context: .
      dockerfile: src/redis/consumers/redis-user-slow/Dockerfile
    ports:
      - '3006:3006'
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
